version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - ./www:/var/www/html
    links:
      - db
  db:
    image: "mysql"
    volumes:
     - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
     - "3306:3306"
